### ISSUE TITLE
bump at enable user open registration

### ISSUE THREAD

**Issue by kalmenchia** [dreamfactorysoftware/ionic-sdk#2]
Hi, 

For Admin Application Version: 2.3.0
      DreamFactory Version: 2.3.0
1. I have installed node and npm using nvm to get the exact version ,
   and successfully see the ionic server -l , with my browser for the 3 UI.
2. i have managed to created a postgres db with service name pg_db and using
   my own dfpkg file , successfully imported and check the tables and
   records at the postgres , was also created and imported without issues.
3. now about the steps to Create a default role for new users and enable open registration
   - i have managed to create the ROLE ,
   - at services tab during edit the user service , when i need to select the Role , to
     Set the Open Reg Role Id to the name of the role I just created. 
     BUMP , i cannot find the ROLE , i created , it always drop down demo ROLE , that
     i cannot find anywhere , not sure when did i created it , is it a bugs ?

What should i do ?

Thanks.
Kalmen

**Comment by todda48** [comment]
Try refreshing the admin console and going back to the User-->Config settings. Is your Role there?

**Comment by kalmenchia** [comment]
not sure what happened , perhaps restarted server or something else but now i can see the ROLE , will continue test it , thanks a lot.

**Comment by kalmenchia** [comment]
but it is working now. Thanks.
